# Generated by Django 4.2.1 on 2024-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCliente', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=15)),
                ('placa', models.CharField(max_length=250)),
                ('veiculo', models.CharField(max_length=250)),
                ('dataVenda', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
    ]
