version: '3'
services:
  salesapp:
    container_name: sales
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbSales
    depends_on:
      - dbSales
    networks:
      - app-network

  dbSales:
    container_name: dbSales
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true