name: pipeline

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r appSales/project/requirements.txt

          

  publish:
      runs-on: ubuntu-latest
      needs: build
      permissions:
        contents: write
        packages: write
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
            package: '*.jar'
        - name: Publish package
          run: pip install -r appSales/project/requirements.txt
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}		  

  test:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install behave
      run:
          pip install behave
    - name: Teste
      run:
          #COMANDO OK > behave appSales/project/features/sales.feature
          python -m pip install --upgrade pip
          pip debug -r appSales/project/requirements.txt
